---
#Ansible playbook starts with ---
-
    hosts: node2
    #Hosts name is the managed system name
    #Declared variable
    vars:
        container_name: myfirstdockercontainer
        container_image: piyush1607kr/demoapp
    
    #Tasks will starts from here
    tasks: 
        - name: install epel release 
          #epel enterprise linux it is being specially created for redhat based system
          dnf: 
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            update_cache: yes
            state: present #present or absent
        - name: Update the RedHat VM
          yum:
            name: yum-utils
            state: present
    


